### ISSUE TITLE
check if specific field failed validation

### ISSUE THREAD

**Issue by kiwo12345** [jpotts18/SwiftValidator#104]
Is there any way to check if a specific field has failed the validation?

I am not using borders for my textfields. Instead I have a UIView styled as a line under my textfield, and I would like to color it red when the textfield fails validation.

And big thanks for sharing this lib!

**Comment by davepatterson** [comment]
Have you tried implementing the validationFailed delegate method? It is called whenever you try to all fields in a form. As a parameter, it has a dictionary of UITextField:ValidationError type. You can use this to see which fields validation failed on.

**Comment by kiwo12345** [comment]
@davepatterson thanks for the help.

But how do I check what field using:
func validationFailed(errors:[UITextField:ValidationError]) {

}

**Comment by kiwo12345** [comment]
@davepatterson I got it working using:
```
func validationFailed(errors:[UITextField:ValidationError]) {
        
        for (field, error) in validator.errors {
            if field == fullNameTextField {
                print("fullname failed")
            }
            if field == emailTextField {
                print("email failed")
            }
        }
    }
```

Thanks for the help!

**Comment by davepatterson** [comment]
Nice! Glad I could help! 👍

**Comment by kiwo12345** [comment]
@davepatterson I went with this instead:

```
validatorReg.styleTransformers(success:{ (validationRule) -> Void in

            if validationRule.textField == self.emailRegisterTextField {
                print("email ok")
            }
            
            }, error:{ (validationError) -> Void in

                if validationError.textField == self.emailRegisterTextField {
                    print("email failed")
                }
        })
```

That way I didnt have to check the failed each time in a foor-loop like in my prev code. Thanks!
