### ISSUE TITLE
Cant use AlphaNumericRule

### ISSUE THREAD

**Issue by otymartin** [jpotts18/SwiftValidator#110]
Hey @jpotts18 

For some reason I can't all the `AlphaNumericRule` in this bloc.

```swift
func registerValidatorRules() {
        validator.registerField(usernameTextField,
                                errorLabel: usernameErrorLabel,
                                rules: [RequiredRule(message: "A username is required!"),
                                MinLengthRule(length: 3, message: "Minimum 3 Characters!"),
                                MaxLengthRule(length: 20, message: "Too many characters: Maximum is 30")])
        
    }
```

**Comment by davepatterson** [comment]
Hey @otymartin. How did you install SwiftValidator? Was it via Cocoapods or did you download the zip from the master page?

**Comment by otymartin** [comment]
CocoaPods @davepatterson

**Comment by davepatterson** [comment]
This is the result of the latest CocoaPod not being consistent with master branch. I have your pod be updated with the master use `pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'`in your Podfile.

**Comment by otymartin** [comment]
That worked greats - thanks @davepatterson 
The fact that it downgraded versions `Installing SwiftValidator 3.0.1 (was 3.0.3)` is no issue?
