### ISSUE TITLE
Does not conform to ValidationDelegate after pod Update

### ISSUE THREAD

**Issue by otymartin** [jpotts18/SwiftValidator#121]
@jpotts18 @davepatterson 
```pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'```

I've been using this for a month now. Today I just ran a quick `pod update`
```Installing SwiftValidator 3.0.1 (was 3.0.1)```
All my view controllers using this library complained that i did not conform to the `ValidationDelegate`

I tried installing other versions `Installing SwiftValidator 3.0.3 (was 3.0.1)`
Same problem. Came back to ```pod 'SwiftValidator', '3.0.1'``` it worked but complained that the `AlphaNumericRule` didnt exist.

**Comment by davepatterson** [comment]
Sorry about that. The master branch actually has the code of version 4.0.0, which adds support for validating fields other than UITextField. Unfortunately upgrading to 4.0.0 breaks 3.x.x, which is the version that master was using before. I recommend updating your code to be consistent with 4.0.0 as it has support for other views. But if you don't want to do that, installing tag 3.0.5 will fix your errors.

`pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '3.0.5'`
