### ISSUE TITLE
fix your specs please

### ISSUE THREAD

**Issue by fmaxx** [jpotts18/SwiftValidator#123]
FROM:
> func validationFailed(errors:[(Validatable ,ValidationError]) {
    // turn the fields to red
    for (field, error) in **validator.errors** {
        if let field = field as? UITextField {

TO:

> func validationFailed(errors:[(Validatable ,ValidationError]) {
    // turn the fields to red
    for (field, error) in **errors** {
        if let field = field as? UITextField {

>

**Comment by davepatterson** [comment]
I definitely missed this. Thanks for fixing @theoziran! 😄
