### ISSUE TITLE
Validator Fields with Mask

### ISSUE THREAD

**Issue by txaiwieser** [jpotts18/SwiftValidator#125]
Is it possible to have a Validator field with a regex mask? like "xxx-xxx-xxxx" 
I want it automatically adds the extra characters. If the user inputs "1234567890" it shows "123-456-7890" but without compromising the validations.
Any tips?

**Comment by davepatterson** [comment]
I think a textField mask is beyond the scope of this library as it really has nothing to do with validation but the appearance of the text. That being said, there are open source projects on github that accomplish just what you're looking for. One off the top of my head is [!link]https://github.com/artemkrachulov/AKMaskField
