### ISSUE TITLE
Set password regex as init parameter

### ISSUE THREAD

**Issue by antonioreyna** [jpotts18/SwiftValidator#140]
Optionally it would be great if you can pass a regexp when setitng the password rule.

**Comment by davepatterson** [comment]
Hi @antonioreyna,

You actually can set the regex when initializing the password rule. Have you tried `PasswordRule(regex: "regex", message: "validation failure message")`?

**Comment by antonioreyna** [comment]
but i checked the code, and my PasswordRule class initializer looks like this:

```
public convenience init(message : String = "Must be 8 characters with 1 uppercase") {
```

**Comment by davepatterson** [comment]
Yeah, that's the convenience initializer. The following line is: `self.init(regex: PasswordRule.regex, message : message)`. It's this line that allows you to do so. Try it out in Xcode. It should work. 💯

**Comment by antonioreyna** [comment]
It worked!! thank you!! im sorry i dont understand swift very well yet, i dont know what that convenience is :) but it works with he regex attribute.

**Comment by davepatterson** [comment]
**Per Apple's documentation:**

Class Inheritance and Initialization

All of a class’s stored properties—including any properties the class inherits from its superclass—must be assigned an initial value during initialization.

Swift defines two kinds of initializers for class types to help ensure all stored properties receive an initial value. These are known as designated initializers and convenience initializers.

Designated Initializers and Convenience Initializers

Designated initializers are the primary initializers for a class. A designated initializer fully initializes all properties introduced by that class and calls an appropriate superclass initializer to continue the initialization process up the superclass chain.

Classes tend to have very few designated initializers, and it is quite common for a class to have only one. Designated initializers are “funnel” points through which initialization takes place, and through which the initialization process continues up the superclass chain.

Every class must have at least one designated initializer. In some cases, this requirement is satisfied by inheriting one or more designated initializers from a superclass, as described in Automatic Initializer Inheritance below.

Convenience initializers are secondary, supporting initializers for a class. You can define a convenience initializer to call a designated initializer from the same class as the convenience initializer with some of the designated initializer’s parameters set to default values. You can also define a convenience initializer to create an instance of that class for a specific use case or input value type.

You do not have to provide convenience initializers if your class does not require them. Create convenience initializers whenever a shortcut to a common initialization pattern will save time or make initialization of the class clearer in intent.

The document from which the above was taken from can be found [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Initialization.html#//apple_ref/doc/uid/TP40014097-CH18-ID204).
