### ISSUE TITLE
expected declaration

### ISSUE THREAD

**Issue by webdevotion** [jpotts18/SwiftValidator#142]
Starting from version `4.0.1` we started to get this issue on our CI server ( and after inspection also on our local test runs with this version ).

```
Carthage/Checkouts/SwiftValidator/SwiftValidator/Rules/ISBNRule.swift:139:5: error: expected declaration
```

Reverted back to `3.0.5` and all is good again.

**Comment by jpotts18** [comment]
Looks like this is an XCode8 issue that broke things. This is referenced all over the place so I'm going to close this.
