### ISSUE TITLE
Unable to install with Carthage

### ISSUE THREAD

**Issue by jaysoifer** [jpotts18/SwiftValidator#144]
Hi,

I've been trying to install SwiftValidator for some time now and, although I'm inexperienced, it seems to me that the issue might not be my fault 😀 ...

    $ xcodebuild -version                                                          
    Xcode 7.3.1
    Build version 7D1014```

    xcode-select -p                                                              
    /Applications/Xcode.app/Contents/Developer

This is the log:

    *** Fetching SwiftValidator
    *** Checking out SwiftValidator at "4.0.1"
    *** xcodebuild output can be found in      /var/folders/y_/266qdqcn20ngwdxwgnplctym0000gn/T/carthage-xcodebuild.O0M7Qv.log
    *** Building scheme "SwiftValidator" in Validator.xcodeproj
    2016-09-05 10:45:12.754 xcodebuild[89784:6467413] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **
    
    The following build commands failed:
       	    CompileSwift normal arm64
       	    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    (2 failures)

And then comes a long list of errors.

Is this an issue or is something specifically related to my install?

**Comment by jaysoifer** [comment]
Just a heads up, I went ahead and installed Alcatraz. Still not working...

BTW, is Alcatraz a dependency? I feel like I missed something...

Updated error message (pretty much the alcatraz line is gone, that's it):
```bash
$ carthage update                                                              [2.3.0]
*** Fetching SwiftValidator
*** Checking out SwiftValidator at "4.0.1"
*** xcodebuild output can be found in /var/folders/y_/266qdqcn20ngwdxwgnplctym0000gn/T/carthage-xcodebuild.ll2IOi.log
*** Building scheme "SwiftValidator" in Validator.xcodeproj
** BUILD FAILED **


The following build commands failed:
       	CompileSwift normal arm64
       	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/jsoifer/Developer/confere-ai-ios/Carthage/Checkouts/SwiftValidator/SwiftValidator/Rules/FullNameRule.swift:33:26: warning: extraneous '_' in parameter: 'value' has no keyword argument name
/Users/jsoifer/Developer/confere-ai-ios/Carthage/Checkouts/SwiftValidator/SwiftValidator/Core/ValidatorDictionary.swift:34:44: warning: extraneous '_' in parameter: 'key' has no keyword argument name
```

(The list of errors goes on, this is just a reference)

Also, not sure if this helps:

```bash
$ xcrun swift -version                                                         [2.3.0]
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
Target: x86_64-apple-macosx10.9
```

**Comment by yanakend** [comment]
@jaysoifer 
I got same error.
https://github.com/jpotts18/SwiftValidator/commits/4.0.1
Probably, SwiftValidator supported swift3. you can see at above link.
So you should change 
```
github "jpotts18/SwiftValidator" "4.0.0"
```

**Comment by davepatterson** [comment]
Did @yanakend's suggestion resolve your issue @jaysoifer?

**Comment by yanakend** [comment]
@davepatterson 
sure. My env is same his version.
```
xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```

**Comment by jaysoifer** [comment]
@davepatterson and @yanakend Sorry for the late reply. I ended up updating xCode recently and that invalidates my question. According to @yanakend I imagine it's ok to close this issue.
Thank you
