### ISSUE TITLE
Pod failed to install iOS 8.4 target

### ISSUE THREAD

**Issue by dhamukrish** [jpotts18/SwiftValidator#148]
Pod failed to install on iOS 8.4 target and below is the error

**Pod Entry**
`pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'swift3-dave'
`

**Error Message**
```
[!] Unable to satisfy the following requirements:

- `SwiftValidator (from `https://github.com/jpotts18/SwiftValidator.git`, branch `swift3-dave`)` required by `Podfile`

Specs satisfying the `SwiftValidator (from `https://github.com/jpotts18/SwiftValidator.git`, branch `swift3-dave`)` dependency were found, but they required a higher minimum deployment target.

```

**Comment by dhamukrish** [comment]
Could you please advise on this

**Comment by davepatterson** [comment]
Which version of swift are you trying to use?

**Comment by dhamukrish** [comment]
Swift 3

**Comment by davepatterson** [comment]
The master is now written in compliance with Swift 3. I updated the README with details of the different active branches.
