### ISSUE TITLE
Branch maintenance 

### ISSUE THREAD

**Issue by ed-mejia** [jpotts18/SwiftValidator#160]
Hey, It is possible to do a quick maintenance on the branches? actually it's looking like this:

![screen shot 2016-10-06 at 11 03 32 am](https://cloud.githubusercontent.com/assets/7431094/19135995/ad97beb0-8bb4-11e6-9104-1e6aafe9ca2b.png)

We can see swift-1.2 branch, 3 different branches for swift 3 😩, the main branch is still not pointing to swift 3 which imho should be the root right now and not a branch.

**Comment by davepatterson** [comment]
That's mostly my fault. I remember a time when you could delete branches after merger but I'm no longer able to do so.

**Comment by davepatterson** [comment]
In the meantime, I'm going to update the readme to detail which branches should be used.
