### ISSUE TITLE
Validator for TextView?

### ISSUE THREAD

**Issue by bettimms** [jpotts18/SwiftValidator#23]
Hi,

Is there any plan to add validator for UITextView?!

Thank you

**Comment by jpotts18** [comment]
What would you like to validate on a UITextView?

**Comment by bettimms** [comment]
The same like in UITextField, except that in UITextView we have multiline. So basically the field is required to fill, or contain only string chars and not numbers or special characters etc.
Everything can be done manually old fashion but since we would start let's say with SwiftValidator then it might be nice to keep the consistency and use throughout whole application no matter if it's UITextField or UITextView.

Thanks

**Comment by jpotts18** [comment]
I could see how others are going to want different views. I think it would probably be good to allow any UIView. I'd be happy to merge this in if you could make that change, write test, and create a PR.
