### ISSUE TITLE
Use of unresolved identifier 'Validator'

### ISSUE THREAD

**Issue by datomnurdin** [jpotts18/SwiftValidator#24]
Since I updated my xcode to 6.3.1, I got this error message

```
/Users/MNurdin/Documents/iOS/xxxxx/Controllers/LoginViewController.swift:20:21: Use of unresolved identifier 'Validator'
```

Please advice. Is there any updated library for swift 1.2?

**Comment by imothee** [comment]
Did you import as 
```
import SwiftValidator
```

At the top of your file? 2.0.7 works (after fixing the optional issue) on 6.3.1 with the above Import

**Comment by datomnurdin** [comment]
Fixed!! Thank you.
