### ISSUE TITLE
Error messages localization

### ISSUE THREAD

**Issue by violabg** [jpotts18/SwiftValidator#31]
It look like localisation of error messages is missing.

**Comment by jpotts18** [comment]
Feel free to add it and send me a PR!

**Comment by mla2c** [comment]
Localization of error messages would be a great feature. Any suggestions how to do it? 

Perhaps simply extending the changes made in https://github.com/jpotts18/SwiftValidator/pull/32 to all rules (i.e. pass message via convenience init)?

**Comment by leodasvacas** [comment]
@mla2c That seems like the best way, then it's up to the user to pass in a localized string. The Rule protocol can be refactored to required a get/set errorMessage property.

**Comment by ismayil097** [comment]
It took me while to add optional error text, then found it in source code. @jpotts18 please add it to Documentation to make it easier for beginners.

` validator.registerField(fieldName, errorLabel: errorLabelfield , rules: [RequiredRule(message: "Your optional errorText")])`

**Comment by jpotts18** [comment]
@ismayil097 please send pull request with updated documentation for beginners
