### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by festaans** [jpotts18/SwiftValidator#37]
Hi, any current efforts on updating SwiftValidator to 2.0?

**Comment by jpotts18** [comment]
Feel free to send pull requests :)

**Comment by i-schuetz** [comment]
You should create a branch for that. So far my knowledge we can't do this, only PR on existing branches. Assuming you don't want to stop supporting Swift 1.2.

**Comment by driver733** [comment]
+1 for swift 2.0

**Comment by i-schuetz** [comment]
https://github.com/jpotts18/SwiftValidator/pull/42, https://github.com/jpotts18/SwiftValidator/pull/46

**Comment by ndmeiri** [comment]
+1 for Swift 2

**Comment by jpotts18** [comment]
I am going to need some more collaborators on this project is anyone interested in helping out?

**Comment by ndmeiri** [comment]
@jpotts18 I might be able to help out in the near future, but I'm pretty busy right now. What are your plans for maintaining the project in the short term?

**Comment by mabeebam** [comment]
+1 for Swift 2.0

**Comment by AdventureOfMar** [comment]
Hello all, I'm new to ios development, is this current branch in development for swift 2.0 or already built for swift 2.0?

**Comment by houmanka** [comment]
Hi guys, Has this been solved? Swift 2 is officially released? I just got bucket load of failed for this Module? Will there be a chance to update the module for Swift 2? Thanks

**Comment by jpotts18** [comment]
The pod has now been updated to Swift 2.0 in the 3.0.0 release. Thanks!
