### ISSUE TITLE
Real Time Validation

### ISSUE THREAD

**Issue by nickchuck** [jpotts18/SwiftValidator#4]
Would be cool to see real time validation where the boxes turn green when the field has valid data. 

Looks great! Nice job Jeff

**Comment by glaucocustodio** [comment]
`validateFieldByKey` method was removed here https://github.com/jpotts18/SwiftValidator/commit/abc729aeac9a52a1b018de35cf4afe31eddc57ba#diff-876721a966e4b01738db78808e73a098L35. Why? We cannot more validate a specif field?

**Comment by jpotts18** [comment]
I decided to move away from the idea of having keys because I realized that the UITextField or a UIView.tag is a unique way to find it anyways.

If you want to validate a specific field you can always just use any of the rules directly like this.  

```swift
// You can validate your field something like this if you want to. 
var isValid = EmailRule().validate(emailTextField.text)

// You can use a tag to create a more unique reference
if emailTextField.tag == UNIQ_ID {
  // run your validation this way. 
}
```
