### ISSUE TITLE
Error order

### ISSUE THREAD

**Issue by ed-mejia** [jpotts18/SwiftValidator#41]
Hi great lib :)

There is an issue with the order returned by the func validationFailed

func validationFailed(errors:[UITextField:ValidationError]) {
    // turn the fields to red
    for (field, error) in validator.errors {
        field.layer.borderColor = UIColor.redColor().CGColor
        field.layer.borderWidth = 1.0
        error.errorLabel?.text = error.errorMessage // works if you added labels
        error.errorLabel?.hidden = false
    }
}

For example if a register this fields:
FirsName
LastName
Email
Phone
Age

I expect the order of the errors in the same way, but it does not return in the same order, so the first error could be Email, and after FirstName, etc..

Is there any quick fix for this?

**Comment by leodasvacas** [comment]
From the [Swift docs](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html):
>Swift’s Dictionary type does not have a defined ordering. To iterate over the keys or values of a dictionary in a specific order, use the sort() method on its keys or values property.

**Comment by jpotts18** [comment]
As far as I can see this is a Swift language issue. Thanks for the help @leodasvacas
