### ISSUE TITLE
Float rule allows letters in input

### ISSUE THREAD

**Issue by richardoti** [jpotts18/SwiftValidator#43]
If I create a float rule like this:
```Objective-C 
validator.registerField(textField, rules: [FloatRule()])
```
And then enter "sdfklnslfd", validation fails. But if I add "64565", so the resulting string in textfield is "sdfklnslfd64565" validation completes with success.

**Comment by jpotts18** [comment]
Wouldn't you just make sure your input field doesn't allow this keyboard option?

**Comment by richardoti** [comment]
That's the exact point of input validation.
It does not matter, how the information gets to the field.
If the input is invalid, validation should fail. And it doesn't.
So, it is a bug in the library.
