### ISSUE TITLE
could not find an overload for init that accepts the supplied arguments

### ISSUE THREAD

**Issue by houmanka** [jpotts18/SwiftValidator#53]
Hi,
I searched a lot for this. No solution :(

When I try to create a custom validator I get this error: 
could not find an overload for init that accepts the supplied arguments

in `DOBRule.swift`
```
import SwiftValidator
class DOBRule: RegexRule {    
    static let regex = "^[0-3]?[0-9].[0-3]?[0-9].(?:[0-9]{2})?[0-9]{2}$"
    convenience init(message : String = "Not a valid SSN"){
        self.init(regex: DOBRule.regex, message : message)
    }
}
```
![screen shot 2015-09-12 at 1 11 25 am](https://cloud.githubusercontent.com/assets/391493/9818311/3cc9826a-58eb-11e5-881a-445601e31a30.png)

Thanks

**Comment by jpotts18** [comment]
What version of Swift are you using?

**Comment by houmanka** [comment]
It was 1.2

Haven`t tested on 2.0 yet.
