### ISSUE TITLE
Can you make it available for Carthage App Manager.

### ISSUE THREAD

**Issue by eddwinpaz** [jpotts18/SwiftValidator#56]
Currently I try to use this library with Carthage but has no success since its not a Shared Scheme.

**Comment by racer1988** [comment]
Agreed,

    github "jpotts18/SwiftValidator"

inside the Cartfile produces following output 

    *** Fetching SwiftValidator
    *** Checking out SwiftValidator at "3.0.1"
    Project "Validator.xcodeproj" has no shared schemes

    If you believe this to be an error, please file an issue with the maintainers at      
    https://github.com/jpotts18/SwiftValidator/issues/new
