### ISSUE TITLE
How can I use this library without installing through cocoapods

### ISSUE THREAD

**Issue by sumitjain7** [jpotts18/SwiftValidator#57]
I want to use SwiftValidator without installing using cocoapods. How to do that?

**Comment by jpotts18** [comment]
You can clone the repo and use the code just like regular swift files. The core should be easy to reuse for whatever your use case is. The test demonstrate how to call the validations from code without using the validator. 

https://github.com/jpotts18/SwiftValidator/blob/master/ValidatorTests/ValidatorTests.swift#L63
