### ISSUE TITLE
Quick Question About Customization

### ISSUE THREAD

**Issue by AdventureOfMar** [jpotts18/SwiftValidator#60]
Hello all, I am new to swift development and I'd like to start off by saying thank you for your pod. My question is this; Is there an easy way to add a parameter for field icon? I.E. I'd like to have an icon next to the textfield that changes colors if invalid or valid

**Comment by jpotts18** [comment]
This is doesn't exactly show how to use it with my library but the general idea would be something like this.

```swift
var textField = UITextField()
if errors.count > 0 {
    textField.rightView = UIImageView(image: UIImage(named: "error-icon"))
} else {
    textField.rightView = UIImageView(image: UIImage(named: "checked-icon"))
}
```
Good luck!

**Comment by AdventureOfMar** [comment]
THANKS SO MUCH!

**Comment by jpotts18** [comment]
:+1:
