### ISSUE TITLE
Add support to others ui components

### ISSUE THREAD

**Issue by glaucocustodio** [jpotts18/SwiftValidator#65]
Hi, here in my work, we started using this library, and then, we added support for some inputs beyond than just `UITextField`, like: `UITextView`, `UISegmentedControl` and `UIStepper`:

```swift
public var textFieldErrors:[UITextField:ValidationError] = [:]
public var textViewErrors:[UITextView:ValidationError] = [:]
public var segmentedControlErrors:[UISegmentedControl:ValidationError] = [:]
public var stepperErrors:[UIStepper:ValidationError] = [:]
	
public var textFieldValidations:[UITextField:ValidationRule] = [:]
public var textViewValidations:[UITextView:ValidationRule] = [:]
public var segmentedControlValidations:[UISegmentedControl:ValidationRule] = [:]
public var stepperValidations:[UIStepper:ValidationRule] = [:]
...
```

Now we are moving to iOS 9 and would like to get the latest SwiftValidator and merge what we have done so far.

My question is: a PR with these changes would be welcome?

Thanks.

**Comment by jpotts18** [comment]
I would be interested in seeing these different inputs in SwiftValidator.

**Comment by glaucocustodio** [comment]
Please, check https://github.com/jpotts18/SwiftValidator/pull/73.

**Comment by ryan-blunden** [comment]
I've checked #73 and the added support for UITextView is essential for a project I'm working on.

**Comment by jpotts18** [comment]
I believe this functionality has been added in #118
