### ISSUE TITLE
No such module 'SwiftValidator'

### ISSUE THREAD

**Issue by sumitjain7** [jpotts18/SwiftValidator#68]
I am using SwiftValidator for so long. Today suddenly Xcode is throwing build failed and showing error : "No such module 'SwiftValidator'"

I am using Xcode 6.4 (Swift 1.2). I installed Swift Validator using pod 
pod 'SwiftValidator', '2.1.1'

Please help

**Comment by ndmeiri** [comment]
Try a clean and re-build.

**Comment by jpotts18** [comment]
I am going to close this issue. Open it again if this is still an issue
