### ISSUE TITLE
Support swift 2?

### ISSUE THREAD

**Issue by mychaelgo** [jpotts18/SwiftValidator#69]

**Comment by jpotts18** [comment]
This library has supported swift 2 for a while now. Is there a specific bug you are finding or is this just a questions?

**Comment by mychaelgo** [comment]
I just installed with cocoa pods, then i include the validator but did'nt work, so i clone this repo and copy paste the lib folder

**Comment by m-etka** [comment]
In Swift 2, I get this error __argument labels '(delegate:)' do not match any available overloads__ for the line 

```swift
validator.validate(delegate:self)
```

Any idea?

**Comment by jernkuan** [comment]
Did you extend ValidationDelegate in the class that contains validator?
You would also need to implement this two functions
    func validationSuccessful()
    func validationFailed(errors: [UITextField:ValidationError])

**Comment by vcardins** [comment]
Have just ```validator.validate(self)``` and it will work

**Comment by hunterlins** [comment]
@vcardins Quick question, where should you place validator.validate(self)? I'm getting an error saying cannot invoke with argument of my ViewController.

**Comment by dkrusenstrahle** [comment]
I have the exact same problem. Any ideas?
