### ISSUE TITLE
Field without RequiredRule should not go through other rules

### ISSUE THREAD

**Issue by ldiqual** [jpotts18/SwiftValidator#79]
Let's take the case of an optional email address:

```
validator.registerField(emailTextField, rules: [EmailRule()]) // Note that there is no RequiredRule()
```

There should be no error when the email textfield is empty.

Maybe `RequiredRule()` should be treated as a special case where, if not in the list of rules, all other rules are skipped? Or maybe have an `OptionalRule`?

**Comment by racer1988** [comment]
You are using a Swift Validator Email Rule
Email rule checks that there is valid email rule inside the textfield.
Which implies that the textfield has to have something inside.

In this case what you want to do is using a custom Email Rule where the check is that there is either a Email or nothing.

This can be done with an alternative Regex.
Maybe you could create a optionalEmailRule and submit it via PR? 

something like that?

    ([A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})?

**Comment by ldiqual** [comment]
@racer1988 Thanks for the followup. I ended up create my own validation code with an optional flag to skip fields if they're null. Closing this issue.
