### ISSUE TITLE
PhoneNumberError

### ISSUE THREAD

**Issue by tnmendex** [jpotts18/SwiftValidator#85]
The example of the phone number don't use the rule phoneNumber

`    validator.registerField(phoneNumberTextField, errorLabel: phoneNumberErrorLabel, rules: [RequiredRule(), MinLengthRule(length: 9)])`

Do you have any example using phoneNumberRule? Because i am having some difficulties

**Comment by davepatterson** [comment]
Hey @tnmendex, the example indeed does not include the actual `PhoneNumberRule()`. To use this rule, simple add `PhoneNumberRule()` to rules (the last argument in registerField). Sticking with the example, you can change line 55 of `ViewController.swift` to: `validator.registerField(phoneNumberTextField, errorLabel: phoneNumberErrorLabel, rules: [PhoneNumberRule()])`
