### ISSUE TITLE
CocoaPod is not same version available on github

### ISSUE THREAD

**Issue by AtheistP3ace** [jpotts18/SwiftValidator#86]
When I pull down from pod install I am not able to call validator.validateField because that function doesn't exist in the code the pod pulled down.

**Comment by davepatterson** [comment]
I checked and confirmed this as well. But is there any reason that you aren't using `validator.validate`? Calling this will call `validator.validateAllFields` which will, as its name suggests, validate all the fields registered to your `validator`.

**Comment by AtheistP3ace** [comment]
Well certain fields I want to validate immediately when the user ends editing them. Seemed better to me at the time I was messing around with this to only validate the specific field they were working on instead of continuing to validate every field every time.

**Comment by davepatterson** [comment]
Understandable. I'm sure @jpotts18 will correct this when he sees it.

**Comment by jpotts18** [comment]
@davepatterson Is this something you can handle now that you are a collaborator?

**Comment by davepatterson** [comment]
@jpotts18 Definitely. I will tackle it tomorrow at the latest.

**Comment by jpotts18** [comment]
Awesome! When you are free let's set up a quick chat and lay out a roadmap for this project. My email is jeff.potter6[at]gmail.com add me and we can set up a hangout or facetime.

**Comment by davepatterson** [comment]
@jpotts18 Yep. My email is davepatterson12@gmail.com, we will definitely chat soon. As for the fix, I added a tag (3.0.3) that is a copy of the master branch so it fixes the issue @AtheistP3ace was having. But unfortunately I am unable to push said tag to CocoaPods because I am not a contributor on the SwiftValidator pod.

**Comment by jpotts18** [comment]
This should be resolved now.

**Comment by AtheistP3ace** [comment]
Thanks for the quick resolution! I'll give it a try later.

**Comment by freak4pc** [comment]
Same issue for me. 
![image](https://cloud.githubusercontent.com/assets/605076/13033481/8381d23e-d320-11e5-8055-8917215a30a6.png)

**Comment by davepatterson** [comment]
This is actually fixed in pod 3.0.3. Use `pod 'SwiftValidator', '3.0.3'` in your Podfile.
