### ISSUE TITLE
pods tvOS support

### ISSUE THREAD

**Issue by keithics** [jpotts18/SwiftValidator#87]
[!] The platform of the target `Pods` (tvOS 9.0) is not compatible with `SwiftValidator (3.0.1)`, which does not support `tvos`.

**Comment by jpotts18** [comment]
Is this also true on 3.0.3 which was just released? Would this need to be iOS 9? I am not very familiar with tvOS

**Comment by keithics** [comment]
yes, it also fails in 3.0.3 , i think you need to target tvOS 9.0+ instead of just iOS 9 in cocoapods
but I will try to manually download it and see if it works fine with tvOS. :smile_cat:

**Comment by davepatterson** [comment]
@keithics Did manually downloading fix your problem?

**Comment by keithics** [comment]
yes, it did. no problems so far. :+1: 

running tvOS on 9.1
