### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by jpotts18** [jpotts18/SwiftValidator#88]
* Add this to Travis CI
* Maybe coveralls? SwiftCov?

**Comment by davepatterson** [comment]
I can handle adding Travis CI.

**Comment by davepatterson** [comment]
I'll look into SwiftCov.

**Comment by davepatterson** [comment]
I looked into this and for iOS projects codecov seems to be better than coveralls. Also, SwiftCov was not necessary as using `-enableCodeCoverage YES` on `xcodebuild test` is enough to generate the code coverage that codecov uses. See the results in #91
